export type IconVariant = {
    day: string;
    night: string;
};

export const conditionCodes: Record<number, IconVariant> = {
    1000: { day: 'sun-1', night: 'moon-1' },
    1003: { day: 'partly-cloudy-1', night: 'partly-cloudy-3' },
    1006: { day: 'mostly-cloudy-2', night: 'mostly-cloudy-2' },
    1009: { day: 'mostly-cloudy-1', night: 'mostly-cloudy-1' },
    1030: { day: 'mist', night: 'mist' },
    1063: { day: 'rain-day', night: 'rain-night' },
    1066: { day: 'snow-day-2', night: 'snow-night-2' },
    1069: { day: 'rain-and-snow', night: 'rain-and-snow' },
    1072: { day: 'snow-day-1', night: 'snow-day-1' },
    1087: { day: 'thunderstorm-day-1', night: 'thunderstorm-night-1' },
    1114: { day: 'snow-day-2', night: 'snow-night-2' },
    1117: { day: 'blizzard', night: 'blizzard' },
    1135: { day: 'fog-1', night: 'fog-1' },
    1147: { day: 'fog-1', night: 'fog-1' },
    1150: { day: 'drizzle', night: 'drizzle' },
    1153: { day: 'drizzle', night: 'drizzle' },
    1168: { day: 'hail-1', night: 'hail-1' },
    1171: { day: 'hail-1', night: 'hail-1' },
    1180: { day: 'rain-day', night: 'rain-night' },
    1183: { day: 'rain-1', night: 'rain-1' },
    1186: { day: 'rain-1', night: 'rain-1' },
    1189: { day: 'rain-1', night: 'rain-1' },
    1192: { day: 'rain-day', night: 'rain-night' },
    1195: { day: 'rain-1', night: 'rain-1' },
    1198: { day: 'hail-1', night: 'hail-1' },
    1201: { day: 'hail-1', night: 'hail-1' },
    1204: { day: 'rain-and-snow', night: 'rain-and-snow' },
    1207: { day: 'rain-and-snow', night: 'rain-and-snow' },
    1210: { day: 'snow-day-2', night: 'snow-night-2' },
    1213: { day: 'snow', night: 'snow' },
    1216: { day: 'snow-day-2', night: 'snow-night-2' },
    1219: { day: 'blizzard', night: 'blizzard' },
    1222: { day: 'snow-day-3', night: 'snow-night-3' },
    1225: { day: 'blizzard', night: 'blizzard' },
    1237: { day: 'hail-1', night: 'hail-1' },
    1240: { day: 'rain-day', night: 'rain-night' },
    1243: { day: 'heavy-rain-day', night: 'heavy-rain-night' },
    1246: { day: 'heavy-rain-day', night: 'heavy-rain-night' },
    1249: { day: 'rain-and-snow', night: 'rain-and-snow' },
    1252: { day: 'rain-and-snow', night: 'rain-and-snow' },
    1255: { day: 'snow-day-2', night: 'snow-night-2' },
    1258: { day: 'snow-day-3', night: 'snow-night-3' },
    1261: { day: 'snow-day-1', night: 'snow-night-1' },
    1264: { day: 'snow-day-2', night: 'snow-night-2' },
    1273: { day: 'thunderstorm-day-1', night: 'thunderstorm-day-1' },
    1276: { day: 'thunderstorm', night: 'thunderstorm' },
    1279: { day: 'thunderstorm-day-1', night: 'thunderstorm-day-1' },
    1282: { day: 'thunderstorm', night: 'thunderstorm' },
};
